  name: Docker
  description: Docker build
  inputs:
    path_dockerfile:
      description: "Path-to-the-Dockerfile"
      required: false
      default: "Dockerfile"
    image_name:
      description: "The-name-for-the-generated-Docker-image."
      required: true
    tag_name:
      description: "The-tag-to-be-added-to-the-final-image."
      required: false
  runs:
    using: composite
    steps:
      - run: |
          dockerfile_path="${{ inputs.path_dockerfile }}"
          image="${{ inputs.image_name }}"
          tag="${{ inputs.tag_name }}"

          if [ -z "$tag" ]; then
            export TAG=$(date +%s)
          else
            export TAG="$tag"
          fi

          docker build . --file "$dockerfile_path" --tag "academy/$image:$TAG"
        shell: bash